#Google Analytics
analytics-id: #leave blank to not use Analytics

#Subtitle
subtitle:
  active: true
  text: Cambridge, UK

#Nav 
nav:
  pages:
    active: true
  social:
    active: true

#Featured images in homepage
featured-img:
  active: false

#Show categories at the end of posts
categories:
  active: false

#Show date and read time under the post title
date-under-post:
  active: true

#Use MathJAX
mathjax:
  active: true

#Show related posts based on categories
related-posts:
  active: false
  title: "You May Also Enjoy"

#Disqus
disqus:
  disqus_shortname: "your_username" #Your disqus shortname. Leave blank to deactivate disqus comments
